version: '3'

services:
  db:
    build:
      context: .
      dockerfile: DbDockerfile
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
  app:
    restart: no
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DB_USER=user
      - DB_NAME=db
      - DB_PASS=password
      - INSTANCE_HOST=db
    develop:
      watch:
        - path: public
          action: sync
          target: var/www/html
        - path: public/api
          action: sync
          target: var/www/html/api
        - path: public/images
          action: sync
          target: var/www/html/images
        - path: public/scripts
          action: sync
          target: var/www/html/scripts
        - path: public/styles
          action: sync
          target: var/www/html/styles
        - path: src/modules
          action: sync
          target: var/www/src/modules
        - path: src/errors
          action: sync
          target: var/www/src/errors
        - path: src/components
          action: sync
          target: var/www/src/components
